services:
  webapp-server:
    build: ./server
    container_name: gpulist-webapp-server
    networks:
      - webapp-network
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env

  webapp-client:
    build: ./client
    container_name: gpulist-webapp-client
    networks:
      - webapp-network
    ports:
      - "5173:80"
    depends_on:
      - webapp-server

  webapp-alt-client:
    build: ./alternative-client
    container_name: gpulist-webapp-alt-client
    networks:
      - webapp-network
    ports:
      - "5174:80"
    depends_on:
      - webapp-server

networks:
  webapp-network:
    driver: bridge
