services:
  webapp-server:
    build: ./server
    container_name: gpulist-webapp-server
    networks:
      - webapp-network
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: test

  webapp-client:
    build: ./client
    container_name: gpulist-webapp-client
    networks:
      - webapp-network
    ports:
      - "5173:80"
    depends_on:
      - webapp-server

  webapp-cypress:
    build: ./tests
    working_dir: /tests
    networks:
      - webapp-network
    env_file:
      - ./tests/.env
    depends_on:
      - webapp-server
      - webapp-client

networks:
  webapp-network:
    driver: bridge
